title: "Form"
description:
  Form is used for sign in/sign up page and payment page.

patterns:
  autocomplete:
    title: "Autocomplete"
    description:
      It is for location input such as province.
  email:
    title: "Email"
    description:
      It is for email input
  password:
    title: "Password"
    description:
      This form is used for password input.
  radio:
    title: "Radio"
    description:
      This is used for choosing between payment method.
  text:
    title: "Text"
    description:
      This is text field which is used for text input like name, address.
    fields:
      - name: field-name
        type: string
        example: "Name"
      - name: field-error
        type: string
        example: "Please provide your name."
